[package]
name = "sudoku-solver"
version = "0.1.0"
authors = ["Luke Arntz <luke@blue42.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
